---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Check for nftables.d
    ansible.builtin.stat:
      path: /etc/nftables.d
    register: p

  - name: Check nftables.d
    ansible.builtin.assert:
      that:
      - p.stat.exists and p.stat.isdir

  - name: Check for nftables.conf
    ansible.builtin.stat:
      path: /etc/nftables.conf
    register: p

  - name: Check nftables.conf
    ansible.builtin.assert:
      that:
      - p.stat.exists

  - name: Check for filter-input.nft
    ansible.builtin.stat:
      path: /etc/nftables.d/filter-input.nft
    register: p

  - name: Check filter-input.nft
    ansible.builtin.assert:
      that:
      - p.stat.exists

  - name: List rules
    ansible.builtin.command:
      cmd: nft list ruleset
    register: nft
    changed_when: false

  - name: Debug rules
    ansible.builtin.debug:
      var: nft

  - name: Check rules
    ansible.builtin.assert:
      that:
      # The whole line is:
      # type filter hook input priority 0; policy drop;
      # However on CentOS will return "priority 0", while Debian will
      # show "priority filter"
      - '"type filter hook input" in nft.stdout'
      - '"type filter hook output" in nft.stdout'

  - name: Service status - active
    ansible.builtin.command:
      cmd: systemctl is-active nftables.service
    register: status
    changed_when: false

  - name: Check service status active
    ansible.builtin.assert:
      that:
      - 'status.stdout == "active"'

  - name: Service status - enabled
    ansible.builtin.command:
      cmd: systemctl is-enabled nftables.service
    register: status
    changed_when: false

  - name: Check service status enabled
    ansible.builtin.assert:
      that:
      - 'status.stdout == "enabled"'
