---
- name: Converge
  hosts: all
  become: true
  vars:
    # Default open ports
    in_tcp_port: '{ ssh, https, http, iscsi-target }'
    in_udp_port: '{ snmp, domain, ntp, bootps }'
    forward_tcp_port: '{ http, https, ssh }'
    forward_udp_port: '{ domain, ntp }'
    # Enabling forwarding and NAT
    firewall_forward_enabled: true
    firewall_nat_enabled: true
    # Definitions
    nft_define_host:
      lan interface:
        name: lan_interface
        value: 'eth0'
      wan interface:
        name: wan_interface
        value: 'eth1'
      lan network:
        name: lan_network
        value: '10.0.1.0/24'
      forward tcp accepted:
        name: forward_tcp_accept
        value: '{{ forward_tcp_port }}'
      forward udp accepted:
        name: forward_udp_accept
        value: '{{ forward_udp_port }}'
    # Forward Definitions
    nft_set_host:
      forward_tcp_accept:
        - type inet_service; flags interval;
        - elements = $forward_tcp_accept
      forward_udp_accept:
        - type inet_service; flags interval;
        - elements = $forward_udp_accept
    # Output rules
    # override default rules allowing all out traffic
    nft_output_host_rules:
      000 policy:
        - type filter hook output priority 0;
      005 global: []
      015 localhost: []
      050 icmp: []
      200 output udp accepted: []
      210 output tcp accepted: []
      250 reset-ssh: []
    # Forwarding rules
    nft_forward_host_rules:
      200 lan to wan tcp:
        - iifname $lan_interface ip saddr $lan_network oifname $wan_interface tcp dport @forward_tcp_accept ct state new accept
      210 wan to lan udp:
        - iifname $lan_interface ip saddr $lan_network oifname $wan_interface udp dport @forward_udp_accept ct state new accept
      220 ssh from wan:
        - iifname $wan_interface oifname $lan_interface ip daddr $lan_network tcp dport ssh ct state new accept
    # NAT Post-routing
    nft_nat_host_postrouting_rules:
      005 masquerade lan to wan:
        - ip saddr $lan_network oifname $wan_interface masquerade
  roles:
    - role: ricsanfre.firewall
